ma27_api_key_authentication:
    resource: "@Ma27ApiKeyAuthenticationBundle/Resources/config/routing/routing.yml"
    prefix: '/api/public'

api:
    resource: '.'
    prefix: '/api'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
